version: '3.7'

services:
    slim:
        build:
            context: .
            dockerfile: "./docker/Dockerfile"
        environment:
            TZ: Europe/Madrid
            docker: "true"
        ports:
            - "80:80"
        restart: "no"
        volumes:
            - .:/var/www/html
            - ./docker/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
